import { Box, Typography } from '@mui/material';
import Head from 'next/head';
import Layout from '../src/components/layout/Layout';

export default function PageNotFoundPage() {
  return (
    <div>
      <Head>
        <title>개발중입니다!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          width: '100%',
          height: '1000px',
          textAlign: 'center',
          alignItems: 'center',
        }}
      >
        <Box>
          <Typography variant="h1">개발중입니다!</Typography>
        </Box>
      </Box>
    </div>
  );
}

PageNotFoundPage.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};
