import { Box } from '@mui/material';
import Head from 'next/head';
import Layout from '../src/components/layout/Layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>WorkForUs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>안녕하세요 반갑습니다.</Box>
    </div>
  );
}

Home.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};
