import { Box } from '@mui/material';
import Head from 'next/head';
import Layout from '../src/components/layout/Layout';
import { useRouter } from 'next/router';
import { useAuth } from '../src/hooks/useAuth';
import { useEffect } from 'react';
import CircularProgress from '@mui/material/CircularProgress';

export default function Home() {
  const router = useRouter();
  const { isLogin, isLoading } = useAuth();

  useEffect(() => {
    if (!isLogin && !isLoading) router.push('/login');
  }, [isLogin, isLoading, router]);

  if (isLoading) {
    return (
      <Box
        sx={{
          display: 'flex',
          width: '100%',
          height: '800px',
          justifyContent: 'center',
        }}
      >
        <Box>
          <CircularProgress />
        </Box>
      </Box>
    );
  }

  return (
    <div>
      <Head>
        <title>WorkForUs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>안녕하세요 반갑습니다.</Box>
    </div>
  );
}

Home.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};
