import { Box } from '@mui/material';
import Head from 'next/head';
import React from 'react';
import LoginLogo from '../src/components/pages/login/LoginLogo';
import RegisterForm from '../src/components/pages/register/RegisterForm';

function RegisterPage() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'center',
          height: '70vh',
          flexDirection: 'column',
        }}
      >
        <LoginLogo />
        <RegisterForm />
      </Box>
    </div>
  );
}

export default RegisterPage;
