import { Box } from '@mui/material';
import Head from 'next/head';
import React, { useEffect } from 'react';
import LoginLogo from '../src/components/pages/login/LoginLogo';
import RegisterForm from '../src/components/pages/register/RegisterForm';
import { useRouter } from 'next/router';
import { useAuth } from '../src/hooks/useAuth';

export default function RegisterPage() {
  const router = useRouter();
  const { isLogin } = useAuth();

  useEffect(() => {
    if (isLogin) router.back();
  }, [isLogin, router]);

  return (
    <div>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'center',
          height: '70vh',
          flexDirection: 'column',
        }}
      >
        <LoginLogo />
        <RegisterForm />
      </Box>
    </div>
  );
}
