import { Box } from '@mui/material';
import Head from 'next/head';
import Layout from '../../src/components/layout/Layout';
import CalendarMenuBox from '../../src/components/pages/calendar/menu/CalendarMenuBox';
import dynamic from 'next/dynamic';

const CalendarMain = dynamic(
  import('../../src/components/pages/calendar/main/CalendarMainBox'),
  { ssr: false },
);

export default function CalendarPage() {
  return (
    <div>
      <Head>
        <title>WorkForUs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex' }}>
        <CalendarMenuBox />
        <CalendarMain />
      </Box>
    </div>
  );
}

CalendarPage.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};
