import { Box } from '@mui/material';
import Head from 'next/head';
import Layout from '../../src/components/layout/Layout';
import CalendarMenuBox from '../../src/components/pages/calendar/menu/CalendarMenuBox';
import dynamic from 'next/dynamic';
import { useRouter } from 'next/router';
import { useAuth } from '../../src/hooks/useAuth';
import { useEffect } from 'react';

const CalendarMain = dynamic(
  import('../../src/components/pages/calendar/main/CalendarMainBox'),
  { ssr: false },
);

export default function CalendarPage() {
  const router = useRouter();
  const { isLogin } = useAuth();

  useEffect(() => {
    if (isLogin) router.push('/login');
  }, [isLogin, router]);
  return (
    <div>
      <Head>
        <title>WorkForUs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex' }}>
        <CalendarMenuBox />
        <CalendarMain />
      </Box>
    </div>
  );
}

CalendarPage.getLayout = function getLayout(page: React.ReactNode) {
  return <Layout>{page}</Layout>;
};
